### ISSUE TITLE
Sending temperature to com port

### ISSUE THREAD

**Issue by NikN52** [openfancontrol/arguscontroller#1]
Hello! Can you add temperature indication on the display for arduino? Those show the temperature of cpu, gpu, etc. on the display connected to the arduino. Simply put, send the required temperatures inside the PC to the com port. Thank you.

**Comment by openfancontrol** [comment]
Sorry for the late reply, but this is not possible and was not our intention for this project. The Argus controller goes one way from uC to PC for temps and fan speeds and the other way for setting fan speed.
But we will have a Windows API soon, with this you can get all values from Argus and send them to whatever gadgets you like (if you know how to control these gadgets of course).
